# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  win-test-job:
    name: go-win-test
    runs-on: windows-latest
    env:
      CGO_ENABLED: 0 
    steps:
    - name: disable-auto-crlf
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: go-vet-test
      run : |
            go vet
            go test -v -timeout 120s -tags "-race" ./... 
  linux-test-job:
    name: go-linux-test
    runs-on: ubuntun-latest
    env:
      CGO_ENABLED: 0 
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: go-vet-test
      run : |
            go vet
            go test -v -timeout 120s -tags "-race" ./... 